local Color, colors, Group, groups, styles = require 'colorbuddy'.setup()
local none = styles.NONE
local bold = styles.bold
local italic = styles.italic
local underline = styles.underline

vim.g.colors_name = 'default'

require("colors/util")
local template = require("colors/colors")

-- Assigned Colors
Color.new('base0', template.base0)
Color.new('base1', template.base1)
Color.new('base2', template.base2)
Color.new('base3', template.base3)
Color.new('base4', template.base4)
Color.new('base5', template.base5)
Color.new('base6', template.base6)
Color.new('base7', template.base7)
Color.new('base8', template.base8)
Color.new('base9', template.base9)
Color.new('base10', template.base10)
Color.new('base11', template.base11)
Color.new('base12', template.base12)
Color.new('base13', template.base13)
Color.new('base14', template.base14)
Color.new('base15', template.base15)

-- HIGHLIGHTS
-- Base Components
Group.new('Bold', colors.none, colors.none, bold)
Group.new('Italic', colors.none, colors.none, italic)
Group.new('Underline', colors.none, colors.none, underline)

Group.new('Normal', colors.base4, colors.base0, none)
Group.new('NormalFloat', colors.none, colors.base0, none)
Group.new('Cursor', colors.none, colors.base4, none)
Group.new('CursorLine', colors.none, colors.base0:light(0.01), none)
Group.new('CursorLineNr', colors.base3, colors.none, none)
Group.new('CursorColumn', colors.none, colors.none, none)
Group.new('Conceal', colors.base15, colors.none, none)
Group.new('Error', colors.base11, colors.none, none)
Group.new('iCursor', colors.base0, colors.base5, none)
Group.new('Pmenu', colors.base4, colors.base0:light(0.08), none)
Group.new('PmenuSbar', colors.base6, colors.base0:light(0.08), none)
Group.new('PmenuSel', colors.base0, colors.base6, bold)
Group.new('PmenuThumb', colors.base2, colors.base6, none)
Group.new('LineNr', colors.base1, colors.none, none)

Group.new("MatchParen", colors.base7, colors.none)
Group.new("NonText", colors.base2, colors.none)
Group.new("SpecialKey", colors.base2, colors.none)
Group.new("SpellBad", colors.base13, colors.none)
Group.new("SpellCap", colors.base13, colors.none)
Group.new("SpellLocal", colors.base4, colors.none)
Group.new("SpellRare", colors.base5, colors.none)
Group.new("Visual", colors.none, colors.base2)
Group.new("VisualNOS", colors.base2, colors.none)
Group.new("healthError", colors.base11, colors.none)
Group.new("healthSuccess", colors.base14, colors.none)
Group.new("healthWarning", colors.base13, colors.none)
Group.new("TermCursorNC", colors.base2, colors.none)
Group.new("Folded", colors.base2, colors.none)
Group.new("FoldColumn", colors.base15, colors.none)
Group.new("SignColumn", colors.base2, colors.none)
Group.new("Directory", colors.base6, colors.none)
Group.new("EndOfBuffer", colors.base1, colors.none)
Group.new("ErrorMsg", colors.base7, colors.none)
Group.new("MsgArea", colors.base3:light(0.1), colors.base0)
Group.new("MoreMsg", colors.base7, colors.none)
Group.new("Question", colors.base3, colors.none)
Group.new("StatusLine", colors.base6, colors.none)
Group.new("StatusLineNC", colors.base3, colors.none)
Group.new("StatusLineTerm", colors.base6, colors.none)
Group.new("StatusLineTermNC", colors.base3, colors.none)
Group.new("WarningMsg", colors.base13, colors.none)
Group.new("WildMenu", colors.base15, colors.none)
Group.new("Search", colors.none, colors.base2)
Group.new("IncSearch", colors.base2, colors.base11)
Group.new("VertSplit", colors.base2, colors.none)

-- Standard Language Groups
Group.new("Boolean", colors.base11, colors.none)
Group.new("Character", colors.base12, colors.none)
Group.new("Comment", colors.base3, colors.none, italic)
Group.new("Conditional", colors.base13, colors.none)
Group.new("Constant", colors.base15, colors.none)
Group.new("Define", colors.base13, colors.none)
Group.new("Delimiter", colors.base5, colors.none)
Group.new("Exception", colors.base7, colors.none)
Group.new("Float", colors.base15, colors.none)
Group.new("Function", colors.base7, colors.none)
Group.new("Identifier", colors.base5, colors.none)
Group.new("Include", colors.base6, colors.none)
Group.new("Keyword", colors.base14, colors.none)
Group.new("Label", colors.base7, colors.none)
Group.new("Number", colors.base15, colors.none)
Group.new("Operator", colors.base6, colors.none)
Group.new("PreProc", colors.base7, colors.none)
Group.new("Repeat", colors.base15, colors.none)
Group.new("Special", colors.base11, colors.none)
Group.new("SpecialChar", colors.base11, colors.none)
Group.new("SpecialComment", colors.base6, colors.none)
Group.new("Statement", colors.base7, colors.none)
Group.new("StorageClass", colors.base7, colors.none)
Group.new("String", colors.base10, colors.none)
Group.new("Structure", colors.base7, colors.none)
Group.new("Tag", colors.base6, colors.none)
Group.new("Todo", colors.base13, colors.none)
Group.new("Type", colors.base7, colors.none)
Group.new("Typedef", colors.base10, colors.none)

--Treesitter
Group.new("TSBoolean", colors.base10, colors.none)
Group.new("TSCharacter", colors.base12, colors.none)
Group.new("TSComment", colors.base3, colors.none, italic)
Group.new("TSConditional", colors.base7, colors.none)
Group.new("TSConstant", colors.base15, colors.none)
Group.new("TSConstBuiltin", colors.base13, colors.none)
Group.new("TSConstructor", colors.base14, colors.none)
Group.new("TSError", colors.none, colors.none, none)
Group.new("TSException", colors.base10, colors.none, italic)
Group.new("TSDefine", colors.base13, colors.none)
Group.new("TSDelimiter", colors.base5, colors.none)
Group.new("TSException", colors.base7, colors.none)
Group.new("TSField", colors.base13, colors.none)
Group.new("TSFloat", colors.base10, colors.none)
Group.new("TSFunction", colors.base11, colors.none)
Group.new("TSFuncBuiltin", colors.base11, colors.none)
Group.new("TSIdentifier", colors.base5, colors.none)
Group.new("TSInclude", colors.base14, colors.none)
Group.new("TSKeyword", colors.base15, colors.none, italic)
Group.new("TSKeywordFunction", colors.base14, colors.none)
Group.new("TSKeywordOperator", colors.base10, colors.none)
Group.new("TSKeywordReturn", colors.base11, colors.none)
Group.new("TSLabel", colors.base15, colors.none)
Group.new("TSMethod", colors.base12, colors.none)
Group.new("TSNamespace", colors.base4, colors.none)
Group.new("TSNumber", colors.base9, colors.none)
Group.new("TSOperator", colors.base13, colors.none)
Group.new("TSParameter", colors.base6, colors.none)
Group.new("TSProperty", colors.base6, colors.none)
Group.new("TSPunctDelimiter", colors.base6, colors.none)
Group.new("TSPunctBracket", colors.base4, colors.none)
Group.new("TSPunctSpecial", colors.base5, colors.none)
Group.new("TSRepeat", colors.base7, colors.none)
Group.new("TSString", colors.base8, colors.none)
Group.new("TSStringRegex", colors.base11, colors.none)
Group.new("TSStringEscape", colors.base9, colors.none)
Group.new("TSStringSpecial", colors.base14, colors.none)
Group.new("TSSymbol", colors.base12, colors.none)
Group.new("TSTag", colors.base10, colors.none)
Group.new("TSTagAttribute", colors.base5, colors.none)
Group.new("TSTagDelimiter", colors.base3, colors.none)
Group.new("TSText", colors.base5, colors.none)
Group.new("TSTextReference", colors.base13, colors.none)
Group.new("TSType", colors.base14, colors.none)
Group.new("TSTypeBuiltin", colors.base14, colors.none)
Group.new("TSVariable", colors.base5, colors.none)
Group.new("TSVariableBuiltin", colors.base5, colors.none)

Group.new("TSDefinitionUsage", colors.none, colors.none, underline)
Group.new("TSDefinition", colors.none, colors.base1:light(0.05), underline)

-- Plugins
-- Tabline
Group.new('TabLineFill', colors.none, colors.base0)
Group.new('BufferOffset', colors.none, colors.base0)

Group.new('BufferCurrent', colors.base0, colors.base6)
Group.new('BufferCurrentSign', colors.base0, colors.base6)
Group.new('BufferCurrentIndex', colors.base0, colors.base6)
Group.new('BufferCurrentMod', colors.base0, colors.base6)

Group.new('BufferVisible', colors.base3, colors.base2)
Group.new('BufferVisibleSign', colors.base3, colors.base2)
Group.new('BufferVisibleIndex', colors.base3, colors.base2)
Group.new('BufferVisibleMod', colors.base3, colors.base2)

Group.new('BufferInactive', colors.base3, colors.base0)
Group.new('BufferInactiveSign', colors.base3, colors.base0)
Group.new('BufferInactiveIndex', colors.base3, colors.base0)
Group.new('BufferInactiveMod', colors.base3, colors.base0)

Group.new('BufferCurrentTarget', colors.base14, colors.base6, bold)
Group.new('BufferInactiveTarget', colors.base14, colors.base1, bold)
Group.new('BufferVisibleTarget', colors.base14, colors.base2, bold)

Group.new("Scrollbar", colors.none, colors.base0:light(0.05))

Group.new("NvimTreeNormal", colors.base4, colors.base0)
Group.new("NvimTreeRootFolder", colors.base7, colors.none, italic)
Group.new("NvimTreeIndentMarker", colors.base2, colors.none)
Group.new("NvimTreeFolderIcon", colors.base6, colors.none)
Group.new("NvimTreeFolderName", colors.base6, colors.none, bold)
Group.new("NvimTreeOpenedFolderName", colors.base6, colors.none, bold)
Group.new("NvimTreeOpenedFile", colors.base7, colors.none, italic)
Group.new("NvimTreeStatuslineNC", colors.none, colors.base1, italic)

Group.new("FloatermBorder", colors.base6, colors.base0)

-- Lsp
Group.new("LspDiagnosticsSignError", colors.base7, colors.base0)
Group.new("LspDiagnosticsSignWarning", colors.base10, colors.base0)
Group.new("LspDiagnosticsSignInformation", colors.base3, colors.base0)
Group.new("LspDiagnosticsSignHint", colors.base2, colors.base0)

Group.new("LspDiagnosticsVirtualTextError", colors.base7, colors.none)
Group.new("LspDiagnosticsVirtualTextWarning", colors.base10, colors.none)
Group.new("LspDiagnosticsVirtualTextInformation", colors.base3, colors.none)
Group.new("LspDiagnosticsVirtualTextHint", colors.base2, colors.none)

Group.new("LspDiagnosticsUnderlineError", colors.base7, colors.none, underline)
Group.new("LspDiagnosticsUnderlineWarning", colors.none, colors.none, underline)
Group.new("LspDiagnosticsUnderlineInformation", colors.none, colors.none)
Group.new("LspDiagnosticsUnderlineHint", colors.none, colors.none)

Group.new("IndentBlanklineChar", colors.base1, colors.none)
Group.new("IndentBlanklineContextChar", colors.base2, colors.none, bold)

Group.new("GitSignsAdd", colors.base10, colors.none)
Group.new("GitSignsAddNr", colors.base10, colors.none)
Group.new("GitSignsAddLn", colors.base5, colors.base10)

Group.new("GitSignsChange", colors.base11, colors.none)
Group.new("GitSignsChangeNr", colors.base11, colors.none)
Group.new("GitSignsChangeLn", colors.base5, colors.base11)

Group.new("GitSignsDelete", colors.base7, colors.none)
Group.new("GitSignsDeleteNr", colors.base7, colors.none)
Group.new("GitSignsDeleteLn", colors.base5, colors.base7)

Group.new("GitSignsCurrentLineBlame", colors.base3, colors.none, italic)

Group.new("CompeDocumentation", colors.none, colors.base0)
Group.new("CompeDocumentationBorder", colors.base6, colors.base0)

Group.new("FloatBorder", colors.base6, colors.base0)
