local Color, colors, Group, groups, styles = require'colorbuddy'.setup()
local none = styles.NONE
local bold = styles.bold
local italic = styles.italic
local underline = styles.underline
local vim = vim

vim.g.colors_name='default'

local template = require("colors/colors")

-- Assigned Colors

Color.new('base0', template.base0)
Color.new('base1', template.base1)
Color.new('base2', template.base2)
Color.new('base3', template.base3)
Color.new('base4', template.base4)
Color.new('base5', template.base5)
Color.new('base6', template.base6)
Color.new('base7', template.base7)
Color.new('base8', template.base8)
Color.new('base9', template.base9)
Color.new('base10',template.base10)
Color.new('base11',template.base11)
Color.new('base12',template.base12)
Color.new('base13',template.base13)
Color.new('base14',template.base14)
Color.new('base15',template.base15)

-- HIGHLIGHTS
-- Base Components
Group.new('Bold', colors.none, colors.none, bold)
Group.new('Italic', colors.none, colors.none, italic)
Group.new('Underline', colors.none, colors.none, underline)


Group.new('Normal', colors.base5, colors.base0, none)
Group.new('Cursor', colors.base0, colors.base8, none)
Group.new('CursorLine', colors.none, colors.base1, none)
Group.new('CursorLineNr', colors.base3, colors.base0, none)
Group.new('CursorColumn', colors.none, colors.base1, none)
Group.new('Conceal', colors.base15, colors.none, none)
Group.new('Error', colors.base11, colors.none, none)
Group.new('iCursor', colors.base0, colors.base9, none)
Group.new('Pmenu', colors.base5, colors.base2, none)
Group.new('PmenuSbar', colors.base8, colors.base2, none)
Group.new('PmenuSel', colors.base0, colors.base8, bold)
Group.new('PmenuThumb', colors.base8, colors.base8, none)
Group.new('LineNr', colors.base0, colors.none, none)

Group.new("MatchParen", colors.base9, colors.none)
Group.new("NonText", colors.base2, colors.none)
Group.new("SpecialKey", colors.base3, colors.none)
Group.new("SpellBad", colors.base13, colors.none)
Group.new("SpellCap", colors.base13, colors.none)
Group.new("SpellLocal", colors.base5, colors.none)
Group.new("SpellRare", colors.base6, colors.none)
Group.new("Visual", colors.base6, colors.base2)
Group.new("VisualNOS", colors.base2, colors.none)
Group.new("healthError", colors.base11, colors.none)
Group.new("healthSuccess", colors.base14, colors.none)
Group.new("healthWarning", colors.base13, colors.none)
Group.new("TermCursorNC", colors.base1, colors.none)
Group.new("Folded", colors.base3, colors.none)
Group.new("FoldColumn", colors.base15, colors.none)
Group.new("SignColumn", colors.base1, colors.none)
Group.new("Directory", colors.base8, colors.none)
Group.new("EndOfBuffer", colors.base0, colors.none)
Group.new("ErrorMsg", colors.base11, colors.none)
Group.new("MoreMsg", colors.base9, colors.none)
Group.new("Question", colors.base4, colors.none)
Group.new("StatusLine", colors.base8, colors.none)
Group.new("StatusLineNC", colors.base4, colors.none)
Group.new("StatusLineTerm", colors.base8, colors.none)
Group.new("StatusLineTermNC", colors.base4, colors.none)
Group.new("WarningMsg", colors.base13, colors.none)
Group.new("WildMenu", colors.base15, colors.none)
Group.new("IncSearch", colors.base6, colors.none)
Group.new("Search", colors.base1, colors.none)
Group.new("VertSplit", colors.base0, colors.none)

-- Tabline
Group.new('BufferCurrent', colors.base0, colors.base8)
Group.new('BufferCurrentSign', colors.base0, colors.base8)
Group.new('BufferCurrentIndex', colors.base0, colors.base8)
Group.new('BufferCurrentMod', colors.base0, colors.base8)

Group.new('BufferVisible', colors.base0, colors.base10)
Group.new('BufferVisibleSign', colors.base0, colors.base10)
Group.new('BufferVisibleIndex', colors.base0, colors.base10)
Group.new('BufferVisibleMod', colors.base0, colors.base10)

Group.new('BufferInactive', colors.base4, colors.base0)
Group.new('BufferInactiveSign', colors.base4, colors.base0)
Group.new('BufferInactiveIndex', colors.base4, colors.base0)
Group.new('BufferInactiveMod', colors.base4, colors.base0)

Group.new('BufferCurrentTarget', colors.base0, colors.base8)
Group.new('BufferInactiveTarget', colors.base0, colors.base8)
Group.new('BufferVisibleTarget', colors.base0, colors.base8)

Group.new('BufferOffset', colors.base0, colors.base1)

Group.new("Boolean", colors.base11, colors.none)
Group.new("Character", colors.base12, colors.none)
Group.new("Comment", colors.base4, colors.none, italic)
Group.new("Conditional", colors.base13, colors.none)
Group.new("Constant", colors.base11, colors.none)
Group.new("Define", colors.base13, colors.none)
Group.new("Delimiter", colors.base7, colors.none)
Group.new("Exception", colors.base9, colors.none)
Group.new("Float", colors.base15, colors.none)
Group.new("Function", colors.base8, colors.none)
Group.new("Identifier", colors.base6, colors.none)
Group.new("Include", colors.base8, colors.none)
Group.new("Keyword", colors.base14, colors.none)
Group.new("Label", colors.base9, colors.none)
Group.new("Number", colors.base15, colors.none)
Group.new("Operator", colors.base8, colors.none)
Group.new("PreProc", colors.base9, colors.none)
Group.new("Repeat", colors.base15, colors.none)
Group.new("Special", colors.base11, colors.none)
Group.new("SpecialChar", colors.base11, colors.none)
Group.new("SpecialComment", colors.base8, colors.none)
Group.new("Statement", colors.base9, colors.none)
Group.new("StorageClass", colors.base9, colors.none)
Group.new("String", colors.base10, colors.none)
Group.new("Structure", colors.base9, colors.none)
Group.new("Tag", colors.base8, colors.none)
Group.new("Todo", colors.base13, colors.none)
Group.new("Type", colors.base9, colors.none)
Group.new("Typedef", colors.base10, colors.none)

Group.new("NvimTreeNormal", colors.base5, colors.base1)
Group.new("NvimTreeIndentMarker", colors.base5, colors.none)
Group.new("NvimTreeFolderIcon", colors.base8, colors.none)
Group.new("NvimTreeFolderName", colors.base6, colors.none, bold)
Group.new("NvimTreeRootFolder", colors.base1, colors.none)
-- Group.new("NvimTreeOpened", colors.base5, colors.base1)

