local opt = vim.opt

opt.termguicolors = true
opt.hidden = true
opt.ignorecase = true
opt.cursorline = true
opt.tabstop = 2
opt.splitbelow = true
opt.splitright = true
opt.mouse = "a"
opt.signcolumn = "auto"
opt.cursorcolumn = true
opt.clipboard = "unnamedplus"
opt.cmdheight = 1
opt.pumheight = 10
opt.updatetime = 250
opt.timeoutlen = 300
opt.expandtab = true
opt.shiftwidth = 2
opt.number = true
opt.numberwidth = 2
opt.scrolloff = 5
opt.background = "light"
opt.relativenumber = true
opt.showmode = false
opt.completeopt = "menuone,noselect,preview,noinsert"
opt.pumblend = 8
opt.winblend = 5
opt.guicursor = "n-v:block-Cursor,i-ci-c:ver10-iCursor,r:hor10-iCursor"
opt.shortmess = "filnxtToOFc"
opt.foldmethod = "expr"
opt.foldexpr = "nvim_treesitter#foldexpr()"
opt.foldlevel = 20

