vim.cmd("let bufferline = get(g:, 'bufferline', {})")

vim.cmd("let bufferline = get(g:, 'bufferline', {})")
vim.cmd("let bufferline.animation = v:true")
vim.cmd("let bufferline.auto_hide = v:false")
vim.cmd("let bufferline.closable = v:true")
vim.cmd("let bufferline.clickable = v:true")
vim.cmd("let bufferline.icons = v:true")
vim.cmd("let bufferline.icon_custom_colors = v:true")
vim.cmd("let bufferline.icon_separator_active = ' '")
vim.cmd("let bufferline.icon_separator_inactive = ' '")
vim.cmd("let bufferline.icon_close_tab = '×'")
vim.cmd("let bufferline.icon_close_tab_modified = '·'")
vim.cmd("let bufferline.maximum_padding = 1")
vim.cmd("let bufferline.semantic_letters = v:true")
vim.cmd("let bufferline.letters ='asdfjkl;ghnmxcvbziowerutyqpASDFJKLGHNMXCVBZIOWERUTYQP'")
vim.cmd("let bufferline.no_name_title = v:null")
