local opts = {
	highlight_hovered_item = false,
	show_guides = true,
	auto_preview = false,
	auto_close = true,
	position = 'right',
  width = 30,
	show_numbers = false,
	show_relative_numbers = false,
	show_symbol_details = true,
	keymaps = {
		close = "<Esc>",
		goto_location = "<Cr>",
		focus_location = "o",
		hover_symbol = "<C-space>",
		rename_symbol = "r",
		code_actions = "a",
	},
	lsp_blacklist = {},
	symbols = {
		File = {icon = "", hl = "TSURI"},
		Module = {icon = "", hl = "TSNamespace"},
		Namespace = {icon = "", hl = "TSNamespace"},
		Package = {icon = "", hl = "TSNamespace"},
		Class = {icon = "", hl = "TSType"},
		Method = {icon = "ƒ", hl = "TSMethod"},
		Property = {icon = "", hl = "TSMethod"},
		Field = {icon = "פּ", hl = "TSField"},
		Constructor = {icon = "", hl = "TSConstructor"},
		Enum = {icon = "練", hl = "TSType"},
		Interface = {icon = "", hl = "TSType"},
		Function = {icon = "", hl = "TSFunction"},
		Variable = {icon = "", hl = "TSConstant"},
		Constant = {icon = "", hl = "TSConstant"},
		String = {icon = "", hl = "TSString"},
		Number = {icon = "", hl = "TSNumber"},
		Boolean = {icon = "⊨", hl = "TSBoolean"},
		Array = {icon = "", hl = "TSConstant"},
		Object = {icon = "", hl = "TSType"},
		Key = {icon = "", hl = "TSType"},
		Null = {icon = "-", hl = "TSType"},
		EnumMember = {icon = "", hl = "TSField"},
		Struct = {icon = "ﳤ", hl = "TSType"},
		Event = {icon = "", hl = "TSType"},
		Operator = {icon = "+", hl = "TSOperator"},
		TypeParameter = {icon = "", hl = "TSParameter"}
	}
}

require"symbols-outline".setup(opts)
