local wk = require 'which-key'
local builtin = require("telescope.builtin")
local gitsigns = require("gitsigns")
local nvim_tree = require("nvim-tree.api").tree
local aerial = require("aerial")
local general_utils = require 'utils.general'
local trouble = require("trouble")

wk.add({
  { "<leader>A",  function() require("spectre").toggle() end,                                             desc = "find & replace" },
  { "<leader>C",  "<cmd>ColorizerToggle<cr>",                                                             desc = "colorizer" },
  { "<leader>f",  function() require("conform").format() end,                                             desc = "format" },
  { "<leader>S",  group = "snippet" },
  { "<leader>Ss", function() require("utils").open_snippets() end,                                        desc = "edit" },
  { "<leader>Su", function() require("utils").refresh_snippets() end,                                     desc = "refresh" },
  { "<leader>T",  group = "treesitter" },
  { "<leader>To", "<cmd>TSPlaygroundToggle<cr>",                                                          desc = "playground" },
  { "<leader>a",  group = "actions" },
  { "<leader>ah", "<cmd>TSHighlightCapturesUnderCursor<cr>",                                              desc = "highlight" },
  { "<leader>as", function() vim.cmd("so") end,                                                           desc = "source" },
  { "<leader>c",  function() vim.fn.setreg("/", "") end,                                                  desc = "clear search" },
  { "<leader>D",  group = "diff" },
  { "<leader>Do", function() vim.cmd.diffget() end,                                                       desc = "get diff" },
  { "<leader>Dp", function() vim.cmd.diffput() end,                                                       desc = "put diff" },
  { "<leader>Du", function() vim.cmd.diffupdate() end,                                                    desc = "update diff" },
  { "<leader>Dt", function() vim.cmd.diffthis() end,                                                      desc = "diff this" },
  { "<leader>e",  function() nvim_tree.toggle() end,                                                      desc = "tree" },
  { "<leader>g",  group = "git" },
  { "<leader>gA", function() vim.cmd("Git add .") end,                                                    desc = "add all" },
  { "<leader>gB", function() gitsigns.toggle_current_line_blame() end,                                    desc = "toggle blame" },
  { "<leader>gL", function() builtin.git_commits() end,                                                   desc = "list commits" },
  { "<leader>gP", function() vim.cmd("Git push") end,                                                     desc = "push" },
  { "<leader>gS", function() vim.cmd("Git status") end,                                                   desc = "status" },
  { "<leader>ga", function() vim.cmd("Git add %") end,                                                    desc = "add current" },
  { "<leader>gb", function() gitsigns.blame_line() end,                                                   desc = "line blame" },
  { "<leader>gc", function() vim.cmd("Git commit") end,                                                   desc = "commit" },
  { "<leader>gl", function() builtin.git_bcommits() end,                                                  desc = "list bcommits" },
  { "<leader>gn", function() gitsigns.toggle_numhl() end,                                                 desc = "signs" },
  { "<leader>gs", function() gitsigns.toggle_signs() end,                                                 desc = "signs" },
  { "<leader>h",  function() builtin.help_tags() end,                                                     desc = "help" },
  { "<leader>l",  group = "lsp" },
  { "<leader>lD", function() vim.diagnostic.enable() end,                                                 desc = "enable" },
  { "<leader>lc", function() vim.lsp.buf.code_action() end,                                               desc = "code action" },
  { "<leader>lt", function() trouble.toggle("diagnostics") end,                                           desc = "file diag." },
  { "<leader>lr", "<cmd>LspRestart<cr>",                                                                  desc = "restart" },
  { "<leader>o",  function() aerial.toggle() end,                                                         desc = "outline" },
  { "<leader>p",  group = "pandoc" },
  { "<leader>pD", function() vim.cmd.edit("~/.local/share/pandoc/defaults.yaml") end,                     desc = "default metadata" },
  { "<leader>pd", function() vim.cmd.edit("~/.local/share/pandoc/templates/default.latex") end,           desc = "default template" },
  { "<leader>pm", function() vim.cmd('silent exec "!make"') end,                                          desc = "make" },
  { "<leader>pp", function() vim.cmd.edit("~/.local/share/pandoc/templates/paper.latex") end,             desc = "paper template" },
  { "<leader>pv", function() vim.cmd('silent exec "!make view"') end,                                     desc = "view" },
  { "<leader>q",  function() require("utils.close").close() end,                                          desc = "close buffer" },
  { "<leader>r",  "<cmd>FloatermNew --height=0.9 --width=0.9 lf<cr>",                                     desc = "lf" },
  { "<leader>s",  group = "settings" },
  { "<leader>sc", function() vim.opt.conceallevel = 0 end,                                                desc = "no-conceal" },
  { "<leader>sh", function() vim.opt.conceallevel = 2 end,                                                desc = "conceal" },
  { "<leader>si", function() general_utils.toggle_status() end,                                           desc = "toggle status bar" },
  { "<leader>so", function() general_utils.toggle_commmand() end,                                         desc = "toggle command bar" },
  { "<leader>ss", function() vim.opt_local.spell = not vim.wo.spell end,                                  desc = "spell" },
  { "<leader>sw", function() vim.opt.wrap = not vim.o.wrap end,                                           desc = "wrap" },
  { "<leader>t",  group = "telescope" },
  { "<leader>tO", function() builtin.vim_options() end,                                                   desc = "vim options" },
  { "<leader>tR", function() builtin.registers() end,                                                     desc = "registers" },
  { "<leader>tc", function() builtin.command_history() end,                                               desc = "command history" },
  { "<leader>to", function() builtin.oldfiles() end,                                                      desc = "old files" },
  { "<leader>tr", function() builtin.live_grep({ cwd = general_utils.find_root() }) end,                  desc = "grep" },
  { "<leader>te", function() builtin.find_files({ cwd = general_utils.find_root() }) end,                 desc = "grep" },
  { "<leader>ts", function() builtin.search_history() end,                                                desc = "searches" },
  { "<leader>z",  group = "files" },
  { "<leader>z=", function() vim.cmd.edit("~/other/dotfiles/config/picom/picom.conf") end,                desc = "picom" },
  { "<leader>zM", function() vim.cmd.edit("~/other/dotfiles/config/nvim/lua/mappings/lsp.lua") end,       desc = "mappings" },
  { "<leader>zb", function() vim.cmd.edit("~/other/dotfiles/config/bspwm/bspwmrc") end,                   desc = "bspwmrc" },
  { "<leader>zh", function() vim.cmd.edit("~/other/dotfiles/config/nvim/lua/highlight.lua") end,          desc = "highlight" },
  { "<leader>zi", function() vim.cmd.edit("~/other/dotfiles/config/nvim/init.lua") end,                   desc = "vimrc" },
  { "<leader>zl", function() vim.cmd.edit("~/other/dotfiles/config/lf/lfrc") end,                         desc = "lfrc" },
  { "<leader>zm", function() vim.cmd.edit("~/other/dotfiles/config/nvim/lua/mappings/general.lua") end,   desc = "mappings" },
  { "<leader>zp", function() vim.cmd.edit("~/other/dotfiles/config/nvim/lua/plugins.lua") end,            desc = "plugins" },
  { "<leader>zs", function() vim.cmd.edit("~/other/dotfiles/config/sxhkd/sxhkdrc") end,                   desc = "sxhkd" },
  { "<leader>zw", function() vim.cmd.edit("~/other/dotfiles/config/nvim/lua/mappings/which-key.lua") end, desc = "mappings" },
  { "<leader>zz", function() vim.cmd.edit("~/other/dotfiles/config/zsh/.zshrc") end,                      desc = "zshrc" },
})
